# Generated by Django 2.2.4 on 2019-08-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general_details',
            old_name='continent_code',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='general_details',
            old_name='continent_name',
            new_name='country_name',
        ),
    ]
