# Generated by Django 2.2.4 on 2019-08-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190818_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_details',
            name='latitude',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='general_details',
            name='longitude',
            field=models.IntegerField(max_length=100),
        ),
    ]
